Migration to 12.x.x
OntimizeWeb/ontimize-web-ng2-playground pull request #228
Opened 2023-05-16 13:04 UTC by patricia-martinez-imatia

2023-05-29 14:23 UTC, daniel-grana requested changes

2023-05-29 14:23 UTC, daniel-grana commented on src/app/app.module.ts
> +    //OGalleryModule
Is this correct? Why are we deleting OGalleryModule?

2023-05-31 08:24 UTC, daniel-grana approved these changes

2023-05-31 08:24 UTC, javierFernandezMendez approved these changes

2024-02-22 10:03 UTC, closed without merging